os:
 - linux 
 - linux-ppc64le
language: node_js
sudo: false
node_js:
  - 6.9.1
install:
  - npm install
script:
  - npm test
after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
